### ISSUE TITLE
check_logfiles.exe

### ISSUE THREAD

**Issue by willemdh** [lausser/check_logfiles#10]
How can I obtain a Windows executable check_logfiles.exe?

I can't open README.exe on Windows 10. 

![image](https://cloud.githubusercontent.com/assets/6462991/11123775/edcb96c4-8961-11e5-83c9-187912510dd3.png)

Also when I try to use the Perl script directly, I get
```
perl .\check_logfiles.pl
Global symbol "%ERRORS" requires explicit package name at .\check_logfiles.pl line 221.
Execution of .\check_logfiles.pl aborted due to compilation errors.
```

Thanks for any info on how to use this on Windows.

**Comment by lausser** [comment]
README.exe ist not an executable file. It's a text file which explains how to create a check_logfiles.exe
When you already have a perl Interpreter on your Windows System, run
perl winconfig.pl
and it will create a plugins-scripts\check_logfiles. This is the final plugin.

**Comment by araujorm** [comment]
Hello.

Just confirmed, latest version, after 6 years this is always reproducible (windows, linux, you name it...). I wonder why nobody else complained... perhaps people just don't try running the command without arguments to see the help?

Just run the script with no arguments. There is a bug in line https://github.com/lausser/check_logfiles/blob/522ebe2326ef480866225ba405dc3be5a8179603/plugins-scripts/check_logfiles.pl#L230

To fix, modify `$ERRORS{UNKNOWN}` with `UNKNOWN` , it's just that simple.

Best regards.
