### ISSUE TITLE
Fail or warn if $protocolsdir is not existing or not writable

### ISSUE THREAD

**Issue by bjoernbessert** [lausser/check_logfiles#11]
Hi,

I've a custom $protocolsdir which i use in check_logfiles. When this directory isn't existing or writable, check_logfiles should be output a warning + corresponding exit code or something else (i'am monitoring the $protocolsdir for new entries/files, therefore i would like to know if there is any problem writing the protocol files)

-Thanks

**Comment by lausser** [comment]
Add 
$options = "protocolfilerrror=critical";
and you'll get an alert. It's in Version 3.7.4
https://labs.consol.de/de/nagios/check_logfiles/index.html
Gerhard
