### ISSUE TITLE
Incorrect perfdata format when tag has white spaces

### ISSUE THREAD

**Issue by adrianlzt** [lausser/check_logfiles#17]
According to the [doc of Icinga](https://docs.icinga.com/latest/en/perfdata.html):

```
the single quotes for the label are optional. Required if spaces, = or ' are in the label
```

When tag have white spaces perfdata is generated incorrectly:
```
$ check_logfiles.pl --logfile=log --tag "some space"
OK - no errors or warnings|some space_lines=0 some space_warnings=0 some space_criticals=0 some space_unknowns=0
```

Should be:
```
OK - no errors or warnings|'some space_lines'=0 'some space_warnings'=0 'some space_criticals'=0 'some space_unknowns'=0
```

**Comment by lausser** [comment]
Sorry, blanks in tags are not supported. Icinga documentation is irrelevant for check_logfiles.

**Comment by adrianlzt** [comment]
If blanks are not supported in tags, should check_logfiles return an error?
