### ISSUE TITLE
Logfiles with no fix name

### ISSUE THREAD

**Issue by sven-borkert** [lausser/check_logfiles#19]
Hi,

it would be super nice if the plugin could work with logfiles like this:

-rw-rw----   1 user      group      1081070 Jan 31 23:59 t20170131000000
-rw-rw----   1 user      group       961113 Feb  1 23:59 t20170201000000
-rw-rw----   1 user      group      1050532 Feb  2 23:59 t20170202000000
-rw-rw----   1 user      group      1471560 Feb  3 23:59 t20170203000000
-rw-rw----   1 user      group       837051 Feb  4 23:59 t20170204000000
-rw-rw----   1 user      group       438710 Feb  5 23:59 t20170205000000
-rw-rw----   1 user      group       990532 Feb  6 17:01 t20170206000000

I could not figure out how to get this working with the otherwise very good check_logfiles plugin.

Regards,

Sven

**Comment by lausser** [comment]
It's
   type => "rotating::uniform",
