### ISSUE TITLE
Download for version 3.8 is incorrect

### ISSUE THREAD

**Issue by adrianlzt** [lausser/check_logfiles#21]
This link has an incorrect content:
https://labs.consol.de/assets/downloads/nagios/check_logfiles-3.8.tar.gz

It seems that it have some mixing between new and old code.
For example, plugins-scripts/Nagios/CheckLogfiles/Search/Journald.pm is missing, but the ChangeLog had the last 3.8 version reference.

Trying to compile this incorrect version was adding the EventLog module so failing in linux hosts.

**Comment by ckujau** [comment]
The [current tarball](https://labs.consol.de/assets/downloads/nagios/check_logfiles-3.8.1.4.tar.gz) has this file included again:

<pre>
$ tar --wildcards -tvzf check_logfiles-3.8.1.4.tar.gz *Journald.pm
-rwxr-xr-x 197609/197121  2597 2017-11-13 07:10 check_logfiles-3.8.1.4/plugins-scripts/Nagios/CheckLogfiles/Search/Journald.pm
</pre>
