### ISSUE TITLE
[REQUEST] Different thresholds for different time range

### ISSUE THREAD

**Issue by Rohlik** [lausser/check_logfiles#37]
Hello and thanks for this best plugin for monitoring logs.

Is it possible to set different warning/critical threshold for different time range?

For example between 6:00-22:00 hours, critical state occur at 5 critical patterns are found, but for time range 22:01-5:59 you need 15 critical patterns to be found.

Can you implement this feature to your script?

**Comment by lausser** [comment]
Sorry, that's not possible. I propose to implement this functionality with script/postscript methods.
