### ISSUE TITLE
CL_CAPTURE_GROUPx not present in $ENV

### ISSUE THREAD

**Issue by jbeaujour** [lausser/check_logfiles#56]
Hello,
Lastest version 3.12 testing and on prod v3.7.3.1
We are trying to capture group and count them in supersmart postcript
@searches = (
        {
                tag              => 'rsync',
                logfile          => '$MY_LOGDIR$/$MY_LOGFILE$',
                type             => 'virtual',
                criticalpatterns => '(total size)',
                options          => 'capturegroups,noprotocol,noperfdata,report=long,nosavethresholdcount'
        }
);

And i'm trying to get : $ENV{CHECK_LOGFILES_CL_CAPTURE_GROUPS}

Is there a mystake in my code (grouping or var) ?
or
this is not true in doc:
"The number of these macros (the highest counter of CL_CAPTURE_GROUPx) can be found in CL_CAPTURE_GROUPS. These macros are best used as environment variables in a handler script."

Thank's

**Comment by lausser** [comment]
And i'm trying to get : $ENV{CHECK_LOGFILES_CL_CAPTURE_GROUP}

Is there a mystake in my code (grouping or var) ?
or
this is not true in doc:
"The number of these macros (the highest counter of CL_CAPTURE_GROUPx) can 
be found in CL_CAPTURE_GROUPS.



Now read again very carefully.

**Comment by jbeaujour** [comment]
Hello
I read and:
- this is not grouping code
- this is not the internet doc (dont modified at this moment)
- there is no environnement variables (you remove this part of my comment in yours)
- this is $ENV{CHECK_LOGFILES_CL_CAPTURE_GROUP**S**} who should be $ENV{CHECK_LOGFILES_CL_CAPTURE_GROUP} (view in your comment)?

??

**Comment by lausser** [comment]
capturegroups is an option used in searches. So the result is used in a search supersmartscript, not in a postscript.
There is CL_CAPTURE_GROUP[1,2,3,...,n] and CL_CAPTURE_GROUPS. There is no CL_CAPTURE_GROUP.
