### ISSUE TITLE
Negative criticalpatterns

### ISSUE THREAD

**Issue by jbeaujour** [lausser/check_logfiles#8]
Hello, it seems negative criticalpatterns don't work in 3.7.1.4.
My log :
Tue Sep 29 17:51:28 2015: relevant files: aide.log
Tue Sep 29 17:51:28 2015: moving to position 0 in /var/log/aide/aide.log
Tue Sep 29 17:51:28 2015: negative pattern All files match AIDE database. Looks okay found.
Tue Sep 29 17:51:28 2015: stopped reading at position 2280
Tue Sep 29 17:51:28 2015: keeping position 2280 and time 1443541885 (Tue Sep 29 17:51:25 2015) for inode 64512:73740 in mind
OK - no errors or warnings|aide_linux_stat_lines=40 aide_linux_stat_warnings=0 aide_linux_stat_criticals=0 aide_linux_stat_unknowns=0

My config :
@searches = (
        {
        tag                     =>      'aide_linux_stat',
        logfile                 =>      '$MY_LOGDIR$/$MY_LOGFILE$',
        criticalpatterns        =>      [
                                        '!All files match AIDE database. Looks okay'
                                        ],
        options                 =>      'allyoucaneat,protocol,nocount',
        }
);

Thank's

**Comment by lausser** [comment]
That's because of Option "nocount", which means: "i don't care how many matches there are". This includes also the negative matches.
There is no reason to set "nocount" except you want to run handler scripts on a match.

**Comment by jbeaujour** [comment]
OK, i remove this option, it work's well. Thank's
