### ISSUE TITLE
Missing documentation for logfilemissing

### ISSUE THREAD

**Issue by rndmh3ro** [lausser/check_logfiles#9]
I guess that this features returns a CRITICAL or WARNING error when the logfile is missing, but I'd like to be sure before using it.
Can you add documentation for this option?

**Comment by lausser** [comment]
Look at http://labs.consol.de/nagios/check_logfiles, i added a line. There's also a new release 3.7.3.1 where "--missinglogfile critical" is possible on the command line.

**Comment by rndmh3ro** [comment]
Thanks!
